// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Credits":return img`
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777ffffffffffffffffff7fffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffff77fffffffffffffffffffffff7fffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffff7fffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffff7ffffffffffffffffffffffffff7fff77ff777ffffffffffffffff222fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff222fffffff7fffffffff7777777fffffffffff7fff77ffff7fff777ffffffffff2222ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffff2222fffffff7fffffffff7fffff777777ff77777fffffffff7ff77ffffffffffff22.2ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffff2222ffffff7fffffffff7ffffff7...77ff7..77ffff7ffff7ff77fffffffffff22222ffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffff22f2ffffff7fffffffff7ffffff77777fff7..7fffff7ffff7ffff7777fffffff2222fffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffff22fffff7fffffffff7ffffff7....7ff77777ffff7ffff7fffffff7fffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffff2fffff77ffffffff7ffffff777777ff77ff77fff7ffff7ffffff7fffffff2fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffff22ffffff777777ffffffffffffffffffffff7ffffffffffff777ffffffff2fffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffffff222fffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff222fffffffffffffffffffffffffffffffffffffffffff222222222222ffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffff2222222222222222222222222222222222222222222ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff77777fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7ffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7fffffff7ffffffffffffff777ffffffffffffffffffffffffffffffffffffffffffff7ffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7fffffff7ffffffffffffff7.77ffffffffffffffffffffffffffffffffffffffffff77ffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff77ffffff7ffffffffffffff7..7ffffffffffffffffffffffffffffffffffffffffff7fffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7ffffff7ff77ffff777ffff777ffffffffffffffffffffffffffffffffffffffffff7fffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7fffff7f77..7ff77fffffff7fff7777fffffff77fffffffffffffffffffffffffff7ffffffff7ffffff7ff77ffff77ffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7fffff7f7...7fff77ffffff7fff7...7ffff77f77ffffffffffffffffffffffffff7ffffffff7fff7ff7777fffffff77ffff77777fffffffffffffffffffffffffffffffffffffffff
fffffffffffff7fffff7f7..77fffff7fffff7fff7...7ffff77ff7ffffffffffffffffffffffffff7fffffff7ffff7ff777fffffffff7fff7ffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7ffff7ff7777fffffff7ffff7fff7..77ffff77fff7fffffffffffffffffffffffff7fffffff7ffff7ff7f7fffffffff7fff7ffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff77777fff7ffff7f77f77ffff7fff777f7ffff7ffff7fffffffffffffffffffffffff777777fff7fff7ff7ff77fff777777fff7777ffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff7fffffff7777ffff77ffffff7ffffff7ffffffffff7ffffffffffffffffffffffff77ffff77ff777fff77ff77ff7....7ffffff77fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffff77f7....7fffffff7fffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777ffffff77ffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffff7ffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff777fffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff7fff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffff7ff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffff7ffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffffff77ffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff777ffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77fff77fffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffff7ff7ff7f7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffffff7ffffffffffff7fffffff7fffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff77ff7f77f7fffffffffffffffff7777ffffffffffffffffffffffffffffffffffffffffffffff7fffffffffff7fffffff7fffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7ffff77ff7fffffffffffffffff7..7ffffffffffffffffffffffffffffffffffffffffffffff7fffffffffff7fffffff7fffffffffffffffffffffffffffffffffffffffffffffffff
fffffffffffff7fffffffff7ffffffff7fffffff777fffff77ffffffffffffffffffffffffffffffff7fffffff7fffffffffff7ffffff77fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7ffffffffff7ff77ffff7fff777ff7ffff77f77fffffffffffffffffffffffffffffff7ffffff7ffffffffffff7ffffff77fffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7ffffffffff7fff7ffff7ff7777fff7fff7fffffffffffffffffffffffffffffffffff7ffff77ff7777ffff7777ffff7777ffffffff7ffffffffffffffffffffffffffffffffffffffff
ffffffffffff7fffffffffff7ff7ffff7fffff77ff77ff7fffffffffffffffffffffffffffffffffff7fff7fff77.77fff7..77fff7777ffff77fff7ffffffffffffffffffffffffffffffffffffffff
ffffffffffff7fffffffffff7ff77ff7fffffff7fff7ff7fffffffffffffffffffffffffffffffffff7ff77fff7..77fff7..77ff7...7fffff7fff77fffffffffffffffffffffffffffffffffffffff
fffffffffffff7ffffffffff77ff7777ffffff77fff77ff77777ffffffffffffffffffffffffffffff777fffff7777777f777777f7..7f7ffff777777fffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffff7777fffff7ffffffffffffffffffffffffffffffffffffff7fffffffffffffff77ff7f777fff7ffffffff7fffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77777777fffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffff7777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffffff77ffffffffffffffffffffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff77ffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff7ff7ffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff888ffffffff77ffffffffff7ffffffffffffffff
ffffffff7f7777777ff77ffffffffffffffffff7ffffffff7fffffffffffffffffffffffffffffffff7ffffffffff7fffffffffffffffffffffffff88.8ffffffffff77ffffffff7fffff7ffffffffff
ffffffff7ffff7ffff77f77777ffffff77777ff7f7fffffffffffffffff777ffffffffffffffffffff7ffffffffff7ffffffffffffffffffffffff8...8ffffff7fffff7fffffff77ffff7ffffffffff
ffffffff7ffff7ffff7ffff7.77fffff7...7ff77777ffffffff777fff77ffffffffffffffffffffff7ffffffffff7ffffffffffffffffffffffff8...8ffffff7fffff7fffffff77fff77ffffffffff
ffffffff7ffff7ffff7ffff7..77ff77....7fff7ff77fffffff7fffff7ffffffffffffffffffffff7fffffffffff7ffff7fffffffffffffffffff8..8ffffffff7fffff7ffffff77fff77ffffffffff
ffffffff77ff77ffff77fff7..77fff7...7ffff7fff7fffffff7ffffff7777ffffffffffffffffff7ffffffffffff7777ffff77ffff777fffffff8.88ffffffff7fffff7ffffff77fff77ffffffffff
fffffffff7f77ffffff7ffff7.777f777..7ffff7fff7fff7fff7fffffffff7ffffffffffffffffff7fffff77ff7ff77ffffffff7ff77ffffffffff8ffffffffff7ffff7fffffff77fff77ffffffffff
ffffffffff77ffffffffffff77fffff7.77ffffffffff7ff77ff7fffffffff7ffffffffffffffffff7fffff7fff7ff77ffffffff7ff77fffffffff88ffffffffff7ffff777fffff7ffff7fffffffffff
fffffffffffffffffffffffffffffff77ffffffffffff7fff7ff7ff7fffff77ffffffffffffffffff7fffff7fff7ff7f7ffff77777fff77fffffff8.888fffffff7fff7777fff777f7777fffffffffff
fffffffffffffffffffffffffffffff77ffffffffffff7fff77ff77ffff777fffffffffffffffffff777ffff7f77ff7f77fff77ff7ffff77ffffff8.8f8fffffff7fff77.7ff7..7f7..7ff7fff7ffff
ffffffffffffffffffffffffffffffff7fffffffffffff7fff7ffffffffffffffffffffffffffffff7ff777f777fffffff77ff77fffffff77ffff8.8fff8ffffff7ff77..7ff7.777...7ff7fff7ffff
ffffffffffffffffffffffffffffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77fff7777ffff8.8fff88fffff7f7f7..7ff7.777...7ff7ff77ffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffffff88fffff88ffff77ff7.777f7.777..77fff7777ffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88ffffff8fffffffff77f7777ff777f77fffff7ffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff88fffffff8ffffffffffffffffffffffffffff7ffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff8ffffffff88fffffffffffffffffffffffffff7ffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffff
fffffff7777ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777fffff
ffffff77ff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffff7fffffffffffffffffffffffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffff7ffff7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
fffffff7ffffffffffffffffffffffffffffffffff77fffffffffffffffff77fffffffffffffffffffffffffffff77ffff77ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffff777ffffffffffffffffffffffffffffffff7fffffffffffff7777fffffffffffffffffffffffffffffff77fff777ffffffffffffffffffffffffffffffffff777fffffffffffffffffffffff
ffffffffff7ffffffffffffffffffffff77ffffffff7ffffffffff777fffffff7fffff7fffffffffffffffffffff77fff7f7fffffffffffffffffffffffffffffffff77ff7ffffffffffffffffffffff
fffffffffff7ff7777fffffffffffffff777fffffff7ffffffffff77ffffffff7ffff77ffffffffffffffffffff7ff7ff7f7f7ff7ffffffffffffffffffffffffffff7fff7ff7fffffffffffffffffff
fffffffffff7f7....7fff7777ffffff7..7fffffff7fffffffffff7ffffffff77ff77fffffffffffffffffffff7ff7f77f7f7f77ffffffffffffffffffffffffffff7ffffff7fffffffffffffffffff
fffffffffff77.....7ff7...7fff777f777fffffff7fffffffffff77ffffffff7f7ffffffffffffffffffffff7fff777ff7f777fff7fff7777f7ffffff7777ffffff7ffffff7fffffffffffffffffff
fffffffffff77......777...7ff77fffff7f77fff7ffffffffff77777ffffffff77fffffffffffffffffffff77ffffffff7fffff7777f77fff7777ff77...7f777fff7fffff777fffffffffffffffff
fffffffffff777.....77...7fff7ffffff7f7.7ff7ffffffffff7f77fffffffff77fffffffffffffffffffff7fffffffff7ff77f7ffff7fff7...7ff7.....77.77ff77fff77fffffffffffffffffff
ffff7fffff7f777...7f7777ffff7ffffff77..7fff7ffffffffffff7ffffffff7f7fffffffffffffffffffff7fffffffff7fff7f7ffff7fff7....7ff777..7...7f77f77ff7fffffffffffffffffff
ffff7fffff7f777..7ff7fffffff7ffffff77..7fff7ffffffffffff7fffffff77f77ffffffffffffffffffff7ffffffffff7ff7f7ffff7fff7...7fffff777....7ff7fffff7fffffffffffffffffff
fffff77ff7ff77f777fff77fffff77ff7ff77..7fff7ffffffffffff7fffffff7fff7ffffffffffffffffffff7ffffffffff7ff7f7fffff7fff7.77fffff777....7ff7fffff7fffffffffffffffffff
fffffff77fff77ffffffff777777ff77fff7777f77f7ffffffffffff7ffffff7ffff77fffffffffffffffffff7ffffffffff7ff7f77f77ffffff7ffff7777ff7...7ff7fffff7ff7ffffffffffffffff
ffffffffffff7.7ffffffffffffffffffffff77f77f7ff7fffffffff7fffff7ffffff77fffffffffffffffffffffffffffff77ffff777fffffffffffff77fff7777fff7fffff7f77ffffffffffffffff
fffffffffffff77fffffffffffffffffffffffffffff777fffffffff7ffff77ffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffff77ffffffffffffffffff
fffffffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffff
fffffffffffff77fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7fffffffffffffffffffffffff
ffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffff7fffffffffffffffffffffffff
ffffffffffffff7ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7ffff7fffffffffffffffffffffffff
fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff77ff77fffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff7777ffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
